### ISSUE TITLE
Move this to org openssh-rust

### ISSUE THREAD

**Issue by NobodyXu** [NobodyXu/tokio-io-utility#5]
This crate is used in openssh-mux-client and openssh-sftp-client and I am not aware of other users, thus I think it is reasonable to move it into the same org as them @jonhoo

**Comment by jonhoo** [comment]
I don't have a strong opinion on this, but yeah, that seems reasonable! We can always move it again later.

**Comment by NobodyXu** [comment]
@jonhoo I've sent an invitation to you on crates.io
